# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Set the version of Python and other tools you might need
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.9"

# Tell Sphinx where to find your configuration
sphinx:
  configuration: Docs/conf.py

# Define the Python installation steps
python:
  install:
    # First, install the project itself (HelixNet) in editable mode
    - method: pip
      path: .
    
    # Next, install the extra requirements needed ONLY for building the docs
    - requirements:
      - docs
